name: prelude
description: Foundation components
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2

dev_dependencies:
  lint_analysis:
    path: ../lint_analysis
  build_runner: ^2.4.7
  freezed: ^2.4.5
  injectable_generator: ^2.4.1