name: design_system
description: Contains all the reusable components
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: 3.22.3

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_svg: 2.0.7
  dotted_border: ^2.1.0
  i69n: ^3.0.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner:
  lint_analysis:
    path: ../lint_analysis

flutter:
  uses-material-design: true
  assets:
    - assets/