name: beneficiary
description: feature to add edit beneficiary
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: 3.22.3

dependencies:
  core:
    path: ../../core
  design_system:
    path: ../../utility/design_system
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2
  app_di:
    path: ../../utility/app_di
  prelude:
    path: ../../utility/prelude
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  lint_analysis:
    path: ../../utility/lint_analysis