name: easy_recharge
description: "Recharge Made Easy"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  app_di:
    path: ../utility/app_di
  auto_route: ^9.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  core:
    path: ../core
  dashboard:
    path: ../feature/dashboard
  beneficiary:
    path: ../feature/beneficiary
  recharge:
    path: ../feature/recharge

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.4.1
  lint_analysis:
    path: ../utility/lint_analysis

flutter:
  uses-material-design: true
